name: t1_outputs
on:
  push:
    branches:
      - main

jobs:
  t1_outputs:
    runs-on: ubuntu-latest
    steps:
      - name: definir outputs v1
        id: var1
        run: |
          echo "output1=valor1" >> $GITHUB_ENV

      - name: imprimir outputs v1
        run: |
          echo "Output 1: ${{ env.output1 }}"

  t2_outputs:
    runs-on: ubuntu-latest
    needs: t1_outputs
    steps:
      - name: imprimir outputs v2
        run: |
          echo "Output 1 from t1:  ${{ env.output2 }}"

      - name: definir outputs v2
        id: var2
        run: |
          echo "output2=Hola Mundo" >> $GITHUB_ENV

  t3_outputs:
    runs-on: ubuntu-latest
    steps:
      - name: leer outputs v2
        run: |
          echo "Output 2 from t2: ${{ needs.t2_outputs.outputs.output2 }}"