name: t1_outputs
on:
  push:
    branches:
      - main

jobs:
  t1_outputs:
    runs-on: ubuntu-latest
    steps:
      - name: definir outputs v1
        id: var1
        run: |
          echo "output1=valor1" >> $GITHUB_OUTPUT

      - name: imprimir outputs v1
        run: |
          echo "Output 1: ${{ steps.var1.outputs.output1 }}"

  t2_outputs:
    runs-on: ubuntu-latest
    outputs:
      var2: ${{ steps.var2.outputs.output2 }}
    steps:
      - name: definir outputs v2
        id: var2
        run: |
          echo "output2=Hola Mundo" >> $GITHUB_OUTPUT

  t3_outputs:
    runs-on: ubuntu-latest
    needs: t2_outputs
    steps:
      - name: imprimir outputs v2
        run: |
          echo "Output 2: ${{ needs.t2_outputs.outputs.var2 }}"
  
